### ISSUE TITLE
Fix confusing documentation around weights and weight tuples

### ISSUE THREAD

**Issue by ajyoon** [ajyoon/chance#7]
The current docs explaining weights and weight tuples have a lot of ambiguity around the word 'weight'. For instance, this gem from `rand.weighted_rand()`:

```
Args:
        weights: (List[(float, float)]): the list of weights where each weight
            is a ``tuple`` of form ``(float, float)`` corresponding to
            ``(outcome, weight)``. All weights outcome values must be numbers.
            Weights with weight ``0`` or less will have no chance to be
            rolled. Must be sorted in increasing order of outcomes.
```

Note that the word 'weight' is used to mean two completely distinct things - one referring to the weight tuple itself, and one referring to the weight of that tuple. This could be easily resolved by replacing the latter with the word 'strength'. For example:

```
Args:
        weights: (List[(float, float)]): the list of weights where each weight
            is a ``tuple`` of form ``(float, float)`` corresponding to
            ``(outcome, strength)``. All weights outcome values must be numbers.
            Weights with strength ``0`` or less will have no chance to be
            rolled. Must be sorted in increasing order of outcomes.
```

The docs would be much easier to understand if this change were made throughout.

**Comment by NathanC** [comment]
How about call each tuple a `weightedValue` consisting of `value` and `weight`, and call the list simply `weightedValues` plural?

(A [named tuple](https://pymotw.com/2/collections/namedtuple.html) may help, although when I tried using those in PyCharm it messed up some of the IDE syntax highlighting and analysis.)

**Comment by ajyoon** [comment]
Older (pre 0.1) versions actually implemented a `Weight` class which was a fixed 2-tuple (essentially a `namedtuple`, but it ended up not seeming worth the user boilerplate to work with. While the functions working with weights could definitely initialize `Weight`s from tuples to reduce user boilerplate, I think it makes the docs a little more confusing than needed. But maybe it can be re-considered...
